apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      run: stateful-nginx
  template:                                 #<-- same template mechanism as for deployments
    metadata:
      labels:
        run: stateful-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:                     #<-- Templates also for the claims
  - metadata:
      name: content
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service   
metadata:
  labels:
    run: stateful-nginx
  name: stateful-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: stateful-nginx
