apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.16
        name: nginx

---
apiVersion: v1
kind: Service                           # <-- definition of a service
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  type: NodePort                        # <-- expose service externally
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
