apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleeper
spec:
  schedule: "*/1 * * * *"                 #<-- Start one job every minute
  successfulJobsHistoryLimit: 1           #<-- only keep the latest job in history
  jobTemplate:                            #<-- this is effectively what we used for the single job 
    spec:
      template:
        spec:
          containers:
          - name: sleeper
            image: alpine
            command: ["/bin/sh",  "-c"]
            args:
              - sleep 10;
                echo Job finished!;
          restartPolicy: Never