apiVersion: batch/v1
kind: Job
metadata:
  name: sleeper
spec:
  template:
    spec:
      containers:
      - name: sleeper
        image: alpine
        command: ["/bin/sh",  "-c"]
        args: 
            - sleep 10; 
              echo Job finished!;
      restartPolicy: Never
